[workspace]
authors = ["4fu <hi@4fwu.com>"]
channels = ["conda-forge"]
name = "localagent"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py312.pypi-dependencies]
zvec = ">=0.2.0, <0.3"
websockets = ">=14, <15"
dashtext = ">=0.0.7, <0.0.8"

[feature.py314.dependencies]
python = "3.14.*"
nodejs = ">=25.7.0,<25.8"
podman = ">=5,<6"
font-ttf-noto-cjk = "*"
font-ttf-noto-emoji = "*"
fontconfig = "*"
nspr = "*"
nss = "*"
at-spi2-core = "*"
xorg-libxcomposite = "*"
xorg-libxdamage = "*"
xorg-libxrandr = "*"
libxkbcommon = "*"
alsa-lib = "*"

[feature.py314.pypi-dependencies]
openai = ">=2.24.0, <3"
msgspec = ">=0.20.0, <0.21"
dotenv = ">=0.9.9, <0.10"
pyyaml = ">=6.0.3, <7"
dashscope = ">=1.25.12, <2"
pillow = ">=11, <12"
websockets = ">=14, <15"
cryptography = ">=45, <46"

[feature.py314.tasks]
localagent_start = "python main.py"
sandbox-build-image = "podman build -t localhost/localagent-sandbox:latest -f docker/sandbox.Dockerfile ."

[environments]
localagent = ["py314"]
zvec = ["py312"]
