from msgspec import field

from ..provider import BaseState


class AgentState(BaseState, kw_only=True):
    project_root: str = field(default=".")
    workspace_root: str = field(default=".")
    cwd: str = field(default="")
    soul_path: str = field(default="SOUL.md")
    host_project_root: str = field(default=".")
    host_workspace_root: str = field(default=".")
    host_skills_path: str = field(default="skills")
    host_soul_path: str = field(default="SOUL.md")
    runtime_project_root: str = field(default=".")
    runtime_workspace_root: str = field(default=".")
    runtime_skills_path: str = field(default="skills")
    runtime_soul_path: str = field(default="SOUL.md")
    runtime_cache_root: str = field(default="")
    containerized: bool = field(default=False)
    is_admin: bool = field(default=False)
    sandboxed: bool = field(default=True)
    readonly: bool = field(default=False)
    bash_enabled: bool = field(default=True)
    allowed_commands: list[str] | None = field(default=None)
    max_read_bytes: int = field(default=200_000)
    max_write_bytes: int = field(default=500_000)
    bash_timeout_ms: int = field(default=30_000)
    max_bash_output_chars: int = field(default=20_000)
    bash_sessions: dict[str, dict] = field(default_factory=dict)
    skills_path: str = field(default="skills")
    hub_url: str = field(default="")
    task_id: str = field(default="")
    current_conversation_id: str = field(default="")
    current_person_id: str = field(default="")
    current_workspace_scope: str = field(default="")
    current_is_multi_party: bool = field(default=False)
    last_memory_id: str = field(default="")
    pending_inbox_ids: list[str] = field(default_factory=list)
    recent_tool_ref_ids: list[str] = field(default_factory=list)
    recent_tool_ref_ids_by_conversation: dict[str, list[str]] = field(default_factory=dict)
    recent_tool_ref_ids_by_memory: dict[str, list[str]] = field(default_factory=dict)
